version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - wanderlust-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/data:/data
    networks:
      - wanderlust-net

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wanderlustdb
      MYSQL_USER: wanderlustuser
      MYSQL_PASSWORD: wanderlustpassword
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - wanderlust-net

networks:
  wanderlust-net:
    driver: bridge

volumes:
  data:
